### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by stephane303**
Adapted doctrine-orm-module depency version

Is this module still compatible with the recent version of doctrine-orm-module ?
What is the situation with it ? Thank you for looking into it.

### CODE REVIEW

**Comment by mpalourdio** [comment]
Your constraint definition is wrong. You can't use wildcard and tilde at the same time.
I suppose that if you stick to "~1.2", it should be ok, as long as you stay to ZF2.

If tests run, then it's ok. (or tests are not relevant)

**Comment by stephane303** [comment]
Yes you are correct about the version, still a bit new to composer ...

**Comment by mpalourdio** [comment]
We should directly stick to ~1.2. Can you update the constraint please ?

Would you please squash your commits too ? Thanks !

Edit : forget what I said, there no 1.2 yet. "~1.1" is fine ! I was confused with doctrine-module

**Comment by mpalourdio** [comment]
We should go to the same php constraints too :https://github.com/doctrine/DoctrineORMModule/blob/master/composer.json#L40

5.5 is old, and has reached EOL IIRC.

**Comment by mpalourdio** [comment]
You must remove 5.5 from .travis.yml build matrix.

**Comment by mpalourdio** [comment]
Looks good now ! Going forward to 5.6 is a good point, as the doctrine stack is 5.6 anyway.
Will merge this soon, and adjust some dependencies before releasing a new tag.

For later, if you submit a PR, please do it from a branch.

Thanks !

**Comment by stephane303** [comment]
Ok, I'll do that. Waiting for your merge, thanks for your reactivity.

**Pull request merged**
